# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "https://joshsullivan.io/"
title = "Josh Sullivan"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"
# newContentEditor = "BBEdit"

hasCJKLanguage = false     # has chinese/japanese/korean
paginate = 10             # Number of articles displayed on the homepage 
rssLimit = 20             # Limit Entry Count to Rss file #  Rss 
# disqusShortname = ""      # disqus_shortname
# googleAnalytics = ""      # UA-XXXXXXXX-X
# copyright = ""            # default: author.name         # author.name

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
[languages.en]
  languageCode = "en"

[permalinks]
post = "/:year/:month/:slug/"
micro = "/micro/:year/:month/:day/:slug/"

[author]                  # essential                   
  name = "Josh Sullivan"

[sitemap]                 # essential                     
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "About"
  weight = 20
  url = "https://blog.joshsullivan.io/about"
[[menu.main]]
  name = "Archives"
  weight = 30
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 40
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 50
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "My Wiki"
  weight = 60
  url = "https://joshisms.io"


[params]
  since = "2019"            # Site creation time          
  homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  # 
  logoTitle = "Josh Sullivan"        # default: the title value    # title
  keywords = ["Technology"]
  description = "A blog by Josh Sullivan"

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  #  front matter archetypes/default.md
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true 
  autoCollapseToc = false                                                                           
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # PhotoSwipe
  # contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file
  
[params.social]                                         
 g-github = "https://github.com/joshcsullivan"